### ISSUE TITLE
Possible NPE in multiple files

### ISSUE THREAD

**Issue by kanavtalwar** [blackrock/protoc-jar-maven-plugin#20]
**Describe the bug**
Various files in the project contains call to .equals() method where in we are calling .equals from an object which could be null and comparing it with a constant value being passed in .equals() call. Better way would be to call CONSTANT.equals(variable) to avoid possible NPE

**To Reproduce**
For example line 93 in MavenUtil.java contains 
n.getNodeName().equals("host") which can give NPE when n is null or n.getNodeName() is null. We can replace it with ("host").equals(n.getNodeName()) and similarly do it for other places as well all over the project

**Expected behavior**
Avoid NPE

**Comment by spensonshih** [comment]
@kanavtalwar , I've approved the pull-request.  In these examples, the NPE won't happen since the variables will never be null, except in MavenUtil.java.  I agree though that it is a good practice to simply use this construct to avoid potential NPE.

In the MavenUtil.java, another potential enhancement would be to parse the settings.xml using the Maven settings API via the `org.apache.maven.settings.DefaultMavenSettingsBuilder` class.

**Comment by spensonshih** [comment]
https://github.com/blackrock/protoc-jar-maven-plugin/pull/21 merged
